<?php

return [

    'list' => [
        'Double Room',
        'Double Room with Private Bathroom',
        'Budget Double Room',
        'Business Double Room with Gym Access',
        'Deluxe Double Room',
        'Deluxe Double Room (1 adult + 1 child)',
        'Deluxe Double Room (1 adult + 2 children)',
        'Deluxe Double Room (2 Adults + 1 Child)',
        'Deluxe Double Room with Balcony',
        'Deluxe Double Room with Balcony and Sea View',
        'Deluxe Double Room with Bath',
        'Deluxe Double Room with Castle View',
        'Deluxe Double Room with Extra Bed',
        'Deluxe Double Room with Sea View',
        'Deluxe Double Room with Shower',
        'Deluxe Double Room with Side Sea View',
        'Deluxe Double or Twin Room',
        'Deluxe King Room',
        'Deluxe Queen Room',
        'Deluxe Room',
        'Deluxe Room (1 adult + 1 child)',
        'Deluxe Room (1 adult + 2 children)',
        'Deluxe Room (2 Adults + 1 Child)',
        'Double Room (1 Adult + 1 Child)',
        'Double Room - Disability Access',
        'Double Room with Balcony',
        'Double Room with Balcony (2 Adults + 1 Child)',
        'Double Room with Balcony (3 Adults)',
        'Double Room with Balcony and Sea View',
        'Double Room with Extra Bed',
        'Double Room with Garden View',
        'Double Room with Lake View',
        'Double Room with Mountain View',
        'Double Room with Patio',
        'Double Room with Pool View',
        'Double Room with Private External Bathroom',
        'Double Room with Sea View',
        'Double Room with Shared Bathroom',
        'Double Room with Shared Toilet',
        'Double Room with Spa Bath',
        'Double Room with Terrace',
        'Economy Double Room',
        'King Room',
        'King Room - Disability Access',
        'King Room with Balcony',
        'King Room with Garden View',
        'King Room with Lake View',
        'King Room with Mountain View',
        'King Room with Pool View',
        'King Room with Roll-In Shower - Disability Access',
        'King Room with Sea View',
        'King Room with Spa Bath',
        'Large Double Room',
        'Queen Room',
        'Queen Room - Disability Access',
        'Queen Room with Balcony',
        'Queen Room with Garden View',
        'Queen Room with Pool View',
        'Queen Room with Sea View',
        'Queen Room with Shared Bathroom',
        'Queen Room with Spa Bath',
        'Small Double Room',
        'Standard Double Room',
        'Standard Double Room with Fan',
        'Standard Double Room with Shared Bathroom',
        'Standard King Room',
        'Standard Queen Room',
        'Superior Double Room',
        'Superior King Room',
        'Superior Queen Room'
    ],

];
